export const vaulthallaQuotes = [
  'He who holds many keys may enter; but only the worthy unlock the vault.',
  'This is no ordinary cloud. This is Vaulthalla.',
  'Glory is not given; it is granted at the gate.',
  'You are not logging in. You are entering the archive of the gods.',
  'Only the sovereign may cross this threshold.',
  'Legacy begins with access. Protect it.',
  'Knowledge is power. In Vaulthalla, it is sacred.',
  'All who enter must remember why they came.',
  'Files don’t die. They ascend.',
  'Your data is not stored. It is enshrined.',
  'The vault does not forget. It remembers with intent.',
  'Access without purpose is heresy.',
  'AES is the steel. Libsodium is the hammer. You are the blacksmith.',
  'A false admin opens doors. A true one forges them shut.',
  'The filesystem is holy. Write with care.',
  'No ad tracking. No telemetry. Only truth.',
  'You may sync your files. But your soul stays local.',
  'TPM-sealed keys. GPG-signed exports. Vaulthalla does not trust blindly.',
  'We don’t patch around failure. We rotate the fucking keys.',
  'Vaults are not mounted. They are consecrated.',
  'Let the weak upload to Google Drive. The strong build Vaulthalla.',
]
